name: automerge
on:
  workflow_dispatch:
# on:
#   schedule:
#     - cron: '* * * * *'

jobs:
  automerge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
